// packages/vue/src/components/UMOEditor.vue
<template>
  <div
    ref="containerRef"
    :class="['umo-editor', className]"
    :style="editorStyle"
  >
    <div class="umo-viewport">
      <div class="umo-viewport-content">
        <div
          v-for="page in pages"
          :key="page.pageNumber"
          :data-page="page.pageNumber"
          class="umo-page"
        >
          <div class="umo-page-content">
            <!-- Page content will be rendered here -->
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useEditor } from '../composables/useEditor'

// ─── Props ──────────────────────────────────────────────────────────────────

const props = defineProps({
  className: {
    type: String,
    default: '',
  },
  config: {
    type: Object,
    default: () => ({}),
  },
})

// ─── Editor Setup ───────────────────────────────────────────────────────────

const {
  document,
  layout,
  pageOptions,
  updateDocument,
  updateSelection,
} = useEditor(props.config)

// ─── Refs ───────────────────────────────────────────────────────────────────

const containerRef = ref(null)

// ─── Computed ───────────────────────────────────────────────────────────────

const pages = computed(() => layout.value?.pages || [])

const editorStyle = computed(() => ({
  display: 'flex',
  flexDirection: 'column',
  height: '100%',
  overflow: 'hidden',
}))
</script>

<style scoped>
.umo-editor {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
  line-height: 1.6;
  color: #333;
}

.umo-editor:focus {
  outline: none;
}

.umo-viewport {
  flex: 1;
  overflow: auto;
  background-color: #f1f5f9;
}

.umo-viewport-content {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 20px;
  padding: 20px;
}

.umo-page {
  background-color: #fff;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  border-radius: 2px;
  position: relative;
}
</style>

// packages/react/src/components/UMOEditor.js
/**
 * UMOEditor Component
 *
 * Main editor component for React.
 * Renders the document with pagination and editing capabilities.
 *
 * Architecture: Framework Adapter — React
 */

import { useRef, useEffect, useCallback } from 'react'
import { useEditor } from './EditorProvider'
import { ViewportContainer } from './ViewportContainer'
import { PageView } from './PageView'

// ─── UMOEditor Component ───────────────────────────────────────────────────

export function UMOEditor({ className = '', style = {} }) {
  const {
    document,
    layout,
    pageOptions,
    updateDocument,
    updateSelection,
  } = useEditor()

  const containerRef = useRef(null)

  // ─── Effects ──────────────────────────────────────────────────────────

  useEffect(() => {
    // Initialize editor
    if (containerRef.current) {
      // Setup event listeners
      const container = containerRef.current

      const handleSelectionChange = () => {
        const selection = window.getSelection()
        if (selection.rangeCount > 0) {
          updateSelection({
            anchor: selection.anchorOffset,
            focus: selection.focusOffset,
          })
        }
      }

      container.addEventListener('selectionchange', handleSelectionChange)

      return () => {
        container.removeEventListener('selectionchange', handleSelectionChange)
      }
    }
  }, [updateSelection])

  // ─── Render ───────────────────────────────────────────────────────────

  return (
    <div
      ref={containerRef}
      className={`umo-editor ${className}`}
      style={{
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        overflow: 'hidden',
        ...style,
      }}
    >
      <ViewportContainer>
        {layout?.pages?.map((page) => (
          <PageView
            key={page.pageNumber}
            page={page}
            pageOptions={pageOptions}
          />
        ))}
      </ViewportContainer>
    </div>
  )
}

// ─── Styles ────────────────────────────────────────────────────────────────

export const editorStyles = `
.umo-editor {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
  line-height: 1.6;
  color: #333;
}

.umo-editor:focus {
  outline: none;
}
`

export default {
  UMOEditor,
  editorStyles,
}
